### ISSUE TITLE
Install Argocd

### ISSUE THREAD

**Issue by mrnim94** [mrnim94/argocd_learning#2]
Install: https://github.com/argoproj/argo-cd/releases  
Docs: https://nimtechnology.com/2021/06/20/argocd-su-dung-argocd-deploy-len-k8s/

**Comment by haotieu2001** [comment]
nhóm 2 có argoCD

**Comment by phonginreallife** [comment]
nhom 3 lam duoc roi a

**Comment by 2000TuHuynh2002** [comment]
nhóm 1 đã install ArgoCD

**Comment by 2000TuHuynh2002** [comment]
![image](https://github.com/mrnim94/argocd_learning/assets/88380100/ebe20ca1-17cc-468c-bc0a-a7a824926994)

**Comment by haotieu2001** [comment]
![image](https://github.com/mrnim94/argocd_learning/assets/62063165/7b009fea-d136-48a6-9c9e-478c300327a6)

**Comment by dknhat2000** [comment]
Team 4 done
![image](https://github.com/mrnim94/argocd_learning/assets/25002040/9440c09b-bc07-4afe-a795-3c228f2e82f1)

**Comment by mrnim94** [comment]
done
