### ISSUE TITLE
Install prometheus to monitor cluster

### ISSUE THREAD

**Issue by mrnim94** [mrnim94/argocd_learning#3]
https://nimtechnology.com/2023/04/02/promethues-install-prometheus-operator-on-kubernetes/

**Comment by haotieu2001** [comment]
![image](https://github.com/mrnim94/argocd_learning/assets/62063165/837bc151-b12a-48ff-aaa9-d3922fbcad74)

**Comment by 2000TuHuynh2002** [comment]
![image](https://github.com/mrnim94/argocd_learning/assets/88380100/645f1a6f-fc6f-4abe-8478-2c6a577aaaea)

**Comment by phonginreallife** [comment]
![image](https://github.com/mrnim94/argocd_learning/assets/112053396/990add3a-e7f3-4b85-986e-31c07a495195)

**Comment by phonginreallife** [comment]
NHOM 3

**Comment by dknhat2000** [comment]
Team 4
![image](https://github.com/mrnim94/argocd_learning/assets/25002040/30f44abf-6311-4deb-86da-64d51d39e80c)

**Comment by mrnim94** [comment]
done
